# Configuration file for the Sports Trivia Pipeline
# Generated by setup.py

# Your Gemini API Key
GEMINI_API_KEY = "AIzaSyC86DvHclKT7_zYmTWcSBnPX6uA3zP7_WE"

# Google Cloud Storage bucket name
GCS_BUCKET_NAME = "trivia-automations-2"

# Optional: Google Cloud Project ID (if different from default)
GCS_PROJECT_ID = None  # Leave as None to use default project

# Optional: Video generation settings
VIDEO_QUALITY = "high"  # "low", "medium", "high"
MAX_VIDEO_LENGTH = 3600  # Maximum video length in seconds (1 hour default)
